INSERT INTO `settings` (`owner_id`, `class`, `key`, `value`, `type`, `context`) VALUES
({{user_id}}, 'Config\\App', 'userCompanyName', 'User Inc.', 'string', NULL),
({{user_id}}, 'Config\\App', 'userCompanyAddress', 'User Company Address And Other Details Here', 'string', NULL),
({{user_id}}, 'Config\\App', 'defaultTimezone', 'Atlantic/St_Helena', 'string', NULL),
({{user_id}}, 'Config\\App', 'defaultLocale', 'en', 'string', NULL),
({{user_id}}, 'Config\\App', 'defaultTheme', 'system', 'string', NULL),
({{user_id}}, 'Config\\App', 'preferredPaymentMethod', '', 'string', NULL),
({{user_id}}, 'Config\\App', 'adminName', 'License Manager', 'string', NULL),
({{user_id}}, 'Config\\App', 'adminEmail', '{{user_email}}', 'string', NULL),
({{user_id}}, 'Config\\App', 'replyToName', 'License Management', 'string', NULL),
({{user_id}}, 'Config\\App', 'replyToEmail', '{{user_email}}', 'string', NULL),
({{user_id}}, 'Config\\App', 'bccName', 'License Manager', 'string', NULL),
({{user_id}}, 'Config\\App', 'bccEmail', '{{user_email}}', 'string', NULL),
({{user_id}}, 'Config\\App', 'sendEmailInvalidChecks', 'on', 'string', NULL),
({{user_id}}, 'Config\\App', 'sendEmailNewLicense', 'on', 'string', NULL),
({{user_id}}, 'Config\\App', 'sendBCCtoResendLicense', '', 'string', NULL),
({{user_id}}, 'Config\\App', 'sendBCCtoLicenseClientNotifications', '', 'string', NULL),
({{user_id}}, 'Config\\App', 'licenseManagerOnUse', 'built-in', 'string', NULL),
({{user_id}}, 'Config\\App', 'licensePrefix', '', 'string', NULL),
({{user_id}}, 'Config\\App', 'licenseSuffix', '', 'string', NULL),
({{user_id}}, 'Config\\App', 'licenseKeyCharsCount', '', 'string', NULL),
({{user_id}}, 'Config\\App', 'licenseServerDomain', '', 'string', NULL),
({{user_id}}, 'Config\\App', 'woocommerceServerDomain', '', 'string', NULL),
({{user_id}}, 'Config\\App', 'licenseServer_Validate_SecretKey', NULL, 'string', NULL),
({{user_id}}, 'Config\\App', 'licenseServer_Create_SecretKey', NULL, 'string', NULL),
({{user_id}}, 'Config\\App', 'autoExpireLicenseKeys', 'on', 'string', NULL),
({{user_id}}, 'Config\\App', 'defaultAllowedDomains', '1', 'string', NULL),
({{user_id}}, 'Config\\App', 'defaultAllowedDevices', '0', 'string', NULL),
({{user_id}}, 'Config\\App', 'emailLogoFile', '', 'string', NULL),
({{user_id}}, 'Config\\App', 'selectedEmailTemplate', 'default_email_template', 'string', NULL),
({{user_id}}, 'Config\\App', 'activationEmailSubject', 'Your License Has Been Activated', 'string', NULL),
({{user_id}}, 'Config\\App', 'activationEmailMessage', 'Your license key was activated successfully', 'string', NULL),
({{user_id}}, 'Config\\App', 'reminderEmailSubject', 'Your License is Expiring Soon', 'string', NULL),
({{user_id}}, 'Config\\App', 'reminderEmailMessage', 'Your license key is about to expire', 'string', NULL),
({{user_id}}, 'Config\\App', 'expiredLicenseEmailSubject', 'Your License Has Expired', 'string', NULL),
({{user_id}}, 'Config\\App', 'expiredLicenseEmailMessage', 'Your license key has expired', 'string', NULL),
({{user_id}}, 'Config\\App', 'sendNewDomainDeviceRegistration', 'on', 'string', NULL),
({{user_id}}, 'Config\\App', 'sendUnregisteredDomainDeviceRegistration', 'on', 'string', NULL),
({{user_id}}, 'Config\\App', 'newDomainDeviceEmailSubject', 'New Domain/Device Activated', 'string', NULL),
({{user_id}}, 'Config\\App', 'newDomainDeviceEmailMessage', 'A new domain/device was registered to your license', 'string', NULL),
({{user_id}}, 'Config\\App', 'unregisteredDomainDeviceEmailSubject', 'Domain/Device Deactivated', 'string', NULL),
({{user_id}}, 'Config\\App', 'unregisteredDomainDeviceEmailMessage', 'A domain/device was deactivated from your license', 'string', NULL),
({{user_id}}, 'Config\\App', 'sendActivationNotification', 'on', 'string', NULL),
({{user_id}}, 'Config\\App', 'sendReminderNotification', 'on', 'string', NULL),
({{user_id}}, 'Config\\App', 'sendExpiredNotification', 'on', 'string', NULL),
({{user_id}}, 'Config\\App', 'numberOfHoursToRemind', '24', 'string', NULL),
({{user_id}}, 'Config\\App', 'default_license_status', 'active', 'string', NULL),
({{user_id}}, 'Config\\App', 'defaultTrialDays', '3', 'string', NULL),
({{user_id}}, 'Config\\App', 'acceptedFileExtensions', '[\"zip\\r\",\"rar\\r\",\"tar\\r\",\"tar.gz\"]', 'string', NULL),
({{user_id}}, 'Config\\App', 'License_Validate_SecretKey', NULL, 'string', NULL),
({{user_id}}, 'Config\\App', 'License_Create_SecretKey', NULL, 'string', NULL),
({{user_id}}, 'Config\\App', 'License_DomainDevice_Registration_SecretKey', NULL, 'string', NULL),
({{user_id}}, 'Config\\App', 'Manage_License_SecretKey', NULL, 'string', NULL),
({{user_id}}, 'Config\\App', 'General_Info_SecretKey', NULL, 'string', NULL),
({{user_id}}, 'Config\\App', 'userEnvatoSyncEnabled', NULL, 'string', NULL),
({{user_id}}, 'Config\\App', 'userEnvatoAPIKey', '', 'string', NULL),
({{user_id}}, 'Config\\App', 'userEnvatoApiCacheTime', '3600', 'string', NULL),
({{user_id}}, 'Config\\App', 'userEnvatoItemCodes', '', 'string', NULL);